-- 기존 성적테이블에서 총점과 평균까지 컬럼으로 조회할 수 있도록 하는 VIEW 생성
CREATE VIEW SUNGTB_VIEW AS 
	SELECT S.*, (KOR+ENG+MAT) TOT, ROUND((KOR+ENG+MAT)/3, 1) "AVG", RANK() OVER(ORDER BY (KOR+ENG+MAT) DESC) "RANK"
	FROM SUNGTB S
	ORDER BY NO;
	
SELECT * FROM SUNGTB;

SELECT * FROM SUNGTB_VIEW;

SELECT * FROM SUNGTB WHERE NAME = '��Ÿ';

UPDATE SUNGTB 
SET NAME = '강타'
WHERE NO = 6;